# Generated by Django 4.1.1 on 2023-01-02 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Penginapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koordinat', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('lokasi', models.CharField(max_length=50)),
                ('Tersisa', models.IntegerField(null=True)),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nginap.jenis')),
            ],
        ),
    ]
