# Generated by Django 4.1.1 on 2023-01-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penginapan',
            old_name='Tersisa',
            new_name='tersisa',
        ),
        migrations.AlterField(
            model_name='penginapan',
            name='lokasi',
            field=models.CharField(max_length=250),
        ),
    ]
