# Generated by Django 4.1.1 on 2023-01-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginap', '0002_rename_tersisa_penginapan_tersisa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penginapan',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto/'),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
