# Generated by Django 4.1.1 on 2023-01-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginap', '0003_penginapan_foto_penginapan_tanggal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penginapan',
            name='tanggal',
        ),
    ]
